### ISSUE TITLE
video turns black after pressing VR button

### ISSUE THREAD

**Issue by rotsuya** [mganeko/aframe#1]
The video turns black after I press VR button.
VRボタンをクリックすると視界が真っ暗になります。

I could fix as a result of deleting these lines.
適当な修正なのでプルリクは出しませんが、ここらへんを削ると直りました。

https://github.com/mganeko/aframe/compare/master...rotsuya:master

**Comment by mganeko** [comment]
ご指摘ありがとうございます。確認してみます。
参考情報として、現象が発生したプラットフォームやブラウザを教えてもらえますか？

**Comment by rotsuya** [comment]
go.html を開いたのは、

- Oculus Go 3.45.70.116334807 user-88830.2550.0 / Browser
- MacBook Pro / Chrome 67.0.3396.99

です。

**Comment by mganeko** [comment]
情報ありがとうございます。
私の方では、こちらの環境で現象は発生しませんでした。

- Oculus Go 3.42.98.111179117 user-27130.12430.180
- MacBook Pro / Chrome 67.0.3396.99 

私のOculus Go のバージョンが古いのが違いかもしれません。もう少し調べてみます。

**Comment by rotsuya** [comment]
検証ありがとうございました。

そちらでは発生しないということは、環境依存のなにかがあるんでしょうね。

こちらでMacとOculusの両方で発生するということは、Blinkのバージョンに依存している？それとも、ハードウェアやソフトウェア以外の何か？

もう少し検証してみます！

**Comment by mganeko** [comment]
Windows 10 Chrome 68 でも試したのですが、現象を起こすことができませんでした。通信環境が関係するのでしょうか..？

試しに、次の2つで動作を確認していただけませんか？

- https://mganeko.github.io/aframe/go2.html ... ご提案の修正方法を適用したもの
- https://mganeko.github.io/aframe/go3.html ... 別の修正方法を試したもの

どちらも私の環境では動作しています（go3.htmlはワーニングは出ます）
よろしくお願いします。

**Comment by rotsuya** [comment]
改めて試してみましたが、go.html, go2.html, go3.htmlとも、正常に動作しました。

前回は、いろんな端末で試してもダメだったんですが…。
A-Frameのバージョンも変わってなさそうだし、何だったんだろう。

実は、前回試したのが25日前なんですよね。
すぐにissueを登録せず、しばらく放置してから登録したのも良くなかったです。

お騒がせして申し訳ありませんでした。closeさせていただきます。また何かあればご報告します。
